### ISSUE TITLE
Any way to use this and debug a maya plugin?

### ISSUE THREAD

**Issue by asierralozano** [NCCA/mayaport#3]
Hi! This is not a bug! just to clarify, but did you know if there is some way to debug a maya plugin using this and the visual studio code debugger? It could be sooo nice!

**Comment by cglynos** [comment]
Haven't done it myself, but have a read at the following:
https://alliance.seas.upenn.edu/~cis660/wiki/index.php?title=Debug_CPP_Plugin

**Comment by asierralozano** [comment]
Im using visual studio code, not visual Studio :(. Thanks anyway!!! 😊
